"""Offline reference generation only. No Molekel evaluator is used here."""

import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import platform
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TMP = ROOT.parent / "tmp"
TMP.mkdir(exist_ok=True)
for key in ("TMPDIR", "TMP", "TEMP"):
    os.environ[key] = str(TMP)
tempfile.tempdir = str(TMP)
os.environ["OMP_NUM_THREADS"] = "1"

import numpy as np
from pyscf import dft, gto, lib, scf

lib.num_threads(1)
OUTPUT = ROOT / "fixtures" / "pyscf"


def export_basis(mol):
    """Export radial normalization and explicit angular polynomials, not values."""
    basis = []
    for shell in range(mol.nbas):
        angular = mol.bas_angular(shell)
        powers = [
            [x, y, angular - x - y]
            for x in range(angular, -1, -1)
            for y in range(angular - x, -1, -1)
        ]
        exponents = mol.bas_exp(shell)
        radial = mol.bas_ctr_coeff(shell) * gto.gto_norm(angular, exponents)[:, None]
        if mol.cart:
            # libcint normalizes s/p angular factors, but not Cartesian d/f/g.
            factor = [np.sqrt(1 / (4 * np.pi)), np.sqrt(3 / (4 * np.pi))]
            angular_weights = np.eye(len(powers)) * (factor[angular] if angular < 2 else 1)
        else:
            angular_weights = gto.cart2sph(angular, normalized=None)
        for contraction in range(mol.bas_nctr(shell)):
            for weights in angular_weights.T:
                basis.append({
                    "center": mol.bas_coord(shell).tolist(),
                    "exponents": exponents.tolist(),
                    "coefficients": radial[:, contraction].tolist(),
                    "terms": [
                        {"powers": p, "weight": float(w)}
                        for p, w in zip(powers, weights) if w != 0
                    ],
                })
    assert len(basis) == mol.nao_nr()
    return basis


def document(mol, name):
    return {
        "id": name, "title": name,
        "atoms": [
            {"element": int(z), "position": p.tolist()}
            for z, p in zip(mol.atom_charges(), mol.atom_coords())
        ],
        "bonds": [], "basis": export_basis(mol), "orbitals": [], "densities": [],
        "grids": [], "surfaces": [],
        "view": {
            "representation": "ball-stick", "positive_color": "#259d86",
            "negative_color": "#cb4e72", "opacity": 0.78, "isovalue": 0.08,
            "field": None,
        },
        "provenance": [
            "Generated by next/tools/generate_references.py with PySCF 2.14.0.",
            "Coordinates in bohr, energies in hartree; coefficients already normalized.",
            "Cartesian d/f/g retain libcint's component-dependent normalization."
            if mol.cart else "Real spherical functions in PySCF AO order.",
        ],
    }


def add_orbitals(doc, coefficients, occupations, energies, spin):
    for i, column in enumerate(coefficients.T):
        doc["orbitals"].append({
            "id": f"{spin}-{i + 1}", "label": f"{spin} MO {i + 1}", "spin": spin,
            "occupation": None if occupations is None else float(occupations[i]),
            "energy": None if energies is None else float(energies[i]),
            "coefficients": column.tolist(),
        })


def add_density(doc, kind, matrix):
    doc["densities"].append({
        "id": kind, "label": f"{kind} density", "kind": kind,
        "matrix": matrix.ravel().tolist(),
    })


def ao_reference(mol, points):
    suffix = "cart" if mol.cart else "sph"
    return mol.eval_gto(f"GTOval_{suffix}_deriv1", points, cutoff=1e-30)


def field_references(mol, doc, ao):
    fields = []
    for orbital in doc["orbitals"]:
        samples = np.einsum("dpa,a->pd", ao, orbital["coefficients"])
        fields.append({"id": orbital["id"], "samples": samples.tolist()})
    for density in doc["densities"]:
        matrix = np.array(density["matrix"]).reshape(mol.nao_nr(), mol.nao_nr())
        # PySCF's independent density and gradient contraction, including non-Hermitian P.
        samples = dft.numint.eval_rho(mol, ao, matrix, xctype="GGA", hermi=0).T
        fields.append({"id": density["id"], "samples": samples.tolist()})
    return fields


def write_fixture(mol, doc, calculation, electrons, orthonormal):
    points = np.vstack((
        mol.atom_coords(),
        [[0, 0, 0], [0.3, 0, 0], [0, -0.7, 0], [0, 0, 1.2],
         [0.31, -0.57, 1.21], [-1.4, 0.6, -0.8], [4.0, -3.0, 2.0],
         [0.125, -0.25, 0.375]],
        np.random.default_rng(7182).uniform(-2, 2, (8, 3)),
    ))
    ao = ao_reference(mol, points)
    origin = np.array([-0.83, 0.27, -0.49])
    axes = np.array([[0.31, 0.04, 0.02], [0.09, 0.23, 0.03], [0.01, 0.06, -0.29]])
    dims = [3, 4, 5]
    grid_points = np.array([
        origin + np.array([x, y, z]) @ axes
        for z in range(dims[2]) for y in range(dims[1]) for x in range(dims[0])
    ])
    grid_ao = ao_reference(mol, grid_points)
    grid_fields = field_references(mol, doc, grid_ao)
    chosen = next((f for f in grid_fields if f["id"] == "total"), grid_fields[-1])
    grid = {
        "id": "reference-grid", "label": "PySCF affine reference",
        "quantity": "density" if chosen["id"] == "total" else "orbital",
        "origin": origin.tolist(), "axes": axes.tolist(), "dims": dims,
        "values": [sample[0] for sample in chosen["samples"]],
    }
    doc["grids"] = [grid]
    doc["view"]["field"] = doc["orbitals"][0]["id"]
    overlap = mol.intor("int1e_ovlp")
    fixture = {
        "producer": {
            "packages": {p: importlib.metadata.version(p) for p in ("pyscf", "numpy", "scipy", "h5py")},
            "python": platform.python_version(), "calculation": calculation,
            "coordinate_unit": "bohr", "ao_order": mol.ao_labels(),
            "ao_convention": "libcint-cartesian-sp-normalized" if mol.cart else "pyscf-real-spherical",
            "expected_backend": "PySCF GTOval_*_deriv1, NumPy MO contraction, PySCF eval_rho",
        },
        "document": doc,
        "reference": {
            "points": points.tolist(), "ao": ao.transpose(1, 2, 0).tolist(),
            "fields": field_references(mol, doc, ao),
            "overlap": overlap.ravel().tolist(), "electrons": electrons,
            "orthonormal_orbitals": orthonormal, "grid_field": chosen["id"],
        },
    }
    target = OUTPUT / f"{doc['id']}.json"
    content = (json.dumps(fixture, separators=(",", ":"), allow_nan=False) + "\n").encode()
    target.write_bytes(content)
    return {"file": target.name, "sha256": hashlib.sha256(content).hexdigest(), "bytes": len(content)}


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest = []
    water = gto.M(
        atom="O 0 0 0; H 0 -1.43233673 1.10715266; H 0 1.43233673 1.10715266",
        unit="Bohr", basis="cc-pvdz", verbose=0,
    )
    rhf = scf.RHF(water)
    rhf.conv_tol = 1e-12
    rhf.kernel()
    assert rhf.converged
    doc = document(water, "water-rhf-ccpvdz")
    add_orbitals(doc, rhf.mo_coeff, rhf.mo_occ, rhf.mo_energy, "spatial")
    add_density(doc, "total", rhf.make_rdm1())
    manifest.append(write_fixture(water, doc, {
        "method": "RHF", "basis": "cc-pVDZ", "converged": True,
        "scf_tolerance": rhf.conv_tol, "energy_hartree": rhf.e_tot,
    }, {"total": 10}, True))

    radical = gto.M(atom="O 0 0 0; H 0 0 1.83", unit="Bohr", basis="sto-3g", spin=1, verbose=0)
    uhf = scf.UHF(radical)
    uhf.conv_tol = 1e-12
    uhf.kernel()
    assert uhf.converged
    doc = document(radical, "hydroxyl-uhf-sto3g")
    for i, spin in enumerate(("alpha", "beta")):
        add_orbitals(doc, uhf.mo_coeff[i], uhf.mo_occ[i], uhf.mo_energy[i], spin)
    alpha, beta = uhf.make_rdm1()
    for kind, matrix in (("alpha", alpha), ("beta", beta), ("total", alpha + beta), ("spin", alpha - beta)):
        add_density(doc, kind, matrix)
    manifest.append(write_fixture(radical, doc, {
        "method": "UHF", "basis": "STO-3G", "converged": True,
        "scf_tolerance": uhf.conv_tol, "energy_hartree": uhf.e_tot,
        "spin_squared": uhf.spin_square()[0],
    }, {"alpha": 5, "beta": 4, "total": 9, "spin": 1}, True))

    shells = [[l, [4.1, 0.17, -0.31], [0.7, 0.58, 0.29], [0.12, 0.24, 0.63]] for l in range(5)]
    for cart in (False, True):
        mol = gto.M(
            atom="He 0.125 -0.25 0.375", unit="Bohr", basis={"He": shells}, cart=cart, verbose=0,
        )
        convention = "cartesian" if cart else "spherical"
        doc = document(mol, f"general-spdfg-{convention}")
        # Five probe orbitals, each confined to one angular momentum and spanning both contractions.
        probes = np.zeros((mol.nao_nr(), 5))
        offsets = mol.ao_loc_nr()
        for shell in range(mol.nbas):
            lo, hi = offsets[shell:shell + 2]
            probes[lo:hi, shell] = np.sin(np.arange(1, hi - lo + 1))
        add_orbitals(doc, probes, None, None, "spatial")
        # A nonsymmetric supplied matrix exercises both derivative product-rule terms.
        transition = np.outer(probes[:, 2], probes[:, 4])
        add_density(doc, "transition", transition)
        manifest.append(write_fixture(mol, doc, {
            "method": "AO-only synthetic general contractions; no SCF or orbital energies",
            "basis": "custom two contractions x three primitives in each S/P/D/F/G shell",
        }, {}, False))
    (OUTPUT / "manifest.json").write_text(json.dumps({"fixtures": manifest}, indent=2) + "\n")
    for item in manifest:
        print(f"{item['file']}: {item['bytes']} bytes, sha256 {item['sha256']}")


if __name__ == "__main__":
    main()
