[workspace]
members = ["crates/molekel-core", "crates/molekel-format", "crates/molekel-wasm", "app/src-tauri"]
default-members = ["crates/molekel-core", "crates/molekel-format", "crates/molekel-wasm"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
sha2 = "0.10"
