
 SET( MOLEKEL_LICENSE
      "Molekel is Copyright (c) 2006-2012 - Swiss National Supercomputing Centre (CSCS)\n"
      "and Ugo Varetto\n"
      "Portions of the source code are Copyright (C) Ugo Varetto\n"
      "Website: http://molekel.cscs.ch\n"
      "This program is free software; you can redistribute it and/or\n"
      "modify it under the terms of the GNU General Public License\n"
      "as published by the Free Software Foundation; either version 2\n"
      "of the License, or (at your option) any later version.\n"
      "\n"
      "This program is distributed in the hope that it will be useful,\n"
      "but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
      "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
      "GNU General Public License for more details.\n"
      "\n"
      "You should have received a copy of the GNU General Public License\n"
      "along with this program; if not, write to the Free Software\n"
      "Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,\n"
      "MA  02110-1301, USA.\n"
      "\n"
      "Molekel is built on top of the following open source libraries, please\n"
      "refer to the specific library's website for license/copyright information:\n"
      "\n"
      "Qt:        http://www.trolltech.com/products/qt\n"
      "VTK:       http://www.vtk.org\n"
      "OpenBabel: http://openbabel.sourceforge.net\n"
      "Coin3D:    http://www.coin3d.org\n"
      "OpenMOIV:  http://www.tecn.upf.es/openMOIV\n"
      "GLEW:      http://glew.sourceforge.net\n"
      "Qwt:       http://qwt.sourceforge.net\n"
