#
# Molekel - Molecular Visualization Program
# Copyright (C) 2006, 2007, 2008, 2009 Swiss National Supercomputing Centre (CSCS)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.
#
# $Author$
# $Date$
# $Revision$
#
##########################################################
# Molekel 5.x
# File included by main CMakeLists.txt file
# list all molekel source files here
# MOC_SRCS contains the files generated by qt moc compiler
##########################################################
SET ( SRCS
      AbstractAtomAnimator.h
      AtomAnimation.h
      MainWindow.h
      MoleculeActorPickCommand.h
      MoleculeCallback.h
      MoleculeVtkCommand.h
      MolekelData.h
      MolekelException.h
      MolekelMolecule.h
      versioninfo.h
      Commands.h
      utility/CommandLine.h
      utility/ElementTable.h
      utility/Geometry.h
      utility/MolekelChemPDBImporter.h
      utility/OBGridData.h
      utility/RAII.h
      utility/Timer.h
      utility/vtkOpenGLGlyphMapper.h
      utility/vtkSoMapper.h
      utility/UniformGrid.h
      utility/vtkMSMSReader.h
      utility/System.h
      utility/events/EventFilter.h
      utility/events/EventLogger.h
      utility/events/EventPlayer.h
      utility/events/EventReader.h
      utility/events/ObjectName.h
      utility/DialogWidget.h
      utility/vtkGLSLShaderActor.h
      utility/shaders/QGLSLShaderEditorWidget.h
      utility/shaders/GLSLShaderException.h
      utility/events/EventPositionTimeWidget.h
      utility/qtfileutils.h
      utility/DoubleSliderWidget.h
      dialogs/MoleculeAnimationDialog.h
      dialogs/TimeStepDialog.h
      dialogs/ComputeElDensSurfaceDialog.h
      dialogs/ImagePlaneProbeDialog.h
      dialogs/GridDataSurfaceDialog.h
      dialogs/MoleculeTrajectoryDialog.h
      dialogs/MoleculeVibrationDialog.h
      dialogs/ExportAnimationDialog.h
      dialogs/SasDialog.h
      dialogs/SesDialog.h
      dialogs/ViewPropertiesDialog.h
      dialogs/ShadersDialog.h
      old/constant.h
      old/molekeltypes.h
      widgets/DisplayPropertyWidget.h
      widgets/MoleculeAnimationModeWidget.h
      widgets/MoleculeRenderingStyleWidget.h
      widgets/MoleculeTrajectoryWidget.h
      widgets/TimeStepWidget.h
      widgets/WorkspaceTreeWidget.h
      widgets/MoleculeElDensSurfaceWidget.h
      widgets/ImagePlaneProbeWidget.h
      widgets/GridDataSurfaceWidget.h
      widgets/SasWidget.h
      widgets/SesWidget.h
      widgets/ShaderWidget.h
      widgets/SpectrumWidget.h
      widgets/DepthPeelingWidget.h
      widgets/AntiAliasingWidget.h
      ${CMAKE_BINARY_DIR}/versioninfo.cpp
      main.cpp
      MainWindow.cpp
      MolekelMolecule.cpp
      MolekelData.cpp
      old/molekeltypes.cpp
      old/readgauss.cpp
      old/readgamess.cpp
      old/calcdens.cpp
      old/utilities.cpp
      old/readmolden.cpp
      resources/icon.cpp
      resources/atomsdata.cpp
      resources/license.cpp
      utility/CommandLine.cpp
      utility/OBGaussianCubeFormat.cpp
      utility/MolekelChemPDBImporter.cpp
      utility/BabelToMOIV.cpp
      utility/vtkMSMSReader.cpp
      utility/System.cpp
      utility/OBMSMSFormat.cpp
      utility/ElementTable.cpp
      utility/MolekelToOpenBabel.cpp
      utility/OBMoldenFormat.cpp
      utility/OBZmatrixFormat.cpp
      utility/OBT41Format.cpp
      utility/events/ObjectName.cpp
      utility/events/EventPlayer.cpp
      utility/events/EventRecorderWidget.cpp
      utility/events/EventPlayerWidget.cpp
      utility/vtkGLSLShaderActor.cpp
      utility/shaders/Shaders.cpp
      utility/shaders/ShaderParameters.cpp
      utility/shaders/QGLSLShaderEditorWidget.cpp
      widgets/MoleculeRenderingStyleWidget.cpp
      widgets/WorkspaceTreeWidget.cpp
      widgets/MoleculeVibrationWidget.cpp
      widgets/MoleculeTrajectoryWidget.cpp
      widgets/MoleculeAnimationModeWidget.cpp
      widgets/TimeStepWidget.cpp
      widgets/MoleculeElDensSurfaceWidget.cpp
      widgets/ImagePlaneProbeWidget.cpp
      widgets/GridDataSurfaceWidget.cpp
      widgets/SpectrumWidget.cpp
      ${MOC_SRCS} )
